
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;


public class ATMPinConfirm extends javax.swing.JFrame {

    int textbox_selection=0;
    LinkedList list= new LinkedList();
    
    /**
     * Creates new form ATM
     */
    public ATMPinConfirm() {
        initComponents();
        readFile();
        
    }

     private void readFile() {
       try {
        File myObj = new File("data.txt");
        Scanner myReader = new Scanner(myObj);
        while (myReader.hasNextLine()) {
          String data = myReader.nextLine();
          if(data.length()>5)
          {
            String[] cus= data.split(";");
           // insert Customer values from the data.txt file to the link list in the System
           list.insertBegin(new Customer(cus[0],cus[1],Double.parseDouble(cus[2]),Integer.parseInt(cus[3]),cus[4],cus[5]));

          }
        }
        myReader.close();
       }
       catch (FileNotFoundException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_r1 = new javax.swing.JLabel();
        lbl_r2 = new javax.swing.JLabel();
        lbl_r3 = new javax.swing.JLabel();
        lbl_r4 = new javax.swing.JLabel();
        lbl_l3 = new javax.swing.JLabel();
        lbl_l4 = new javax.swing.JLabel();
        lbl_l1 = new javax.swing.JLabel();
        lbl_l2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_pin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_enter_card = new javax.swing.JTextField();
        btn_n1 = new javax.swing.JButton();
        btn_n2 = new javax.swing.JButton();
        btn_n3 = new javax.swing.JButton();
        btn_n6 = new javax.swing.JButton();
        btn_n5 = new javax.swing.JButton();
        btn_n4 = new javax.swing.JButton();
        btn_n9 = new javax.swing.JButton();
        btn_n7 = new javax.swing.JButton();
        btn_n8 = new javax.swing.JButton();
        btn_n_dot = new javax.swing.JButton();
        btn_n_blank = new javax.swing.JButton();
        btn_n0 = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_enter = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(498, 763));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bank_logo_2.png"))); // NOI18N

        lbl_r1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round.png"))); // NOI18N

        lbl_r2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round.png"))); // NOI18N

        lbl_r3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round.png"))); // NOI18N

        lbl_r4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round.png"))); // NOI18N

        lbl_l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round.png"))); // NOI18N

        lbl_l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round.png"))); // NOI18N

        lbl_l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round.png"))); // NOI18N

        lbl_l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(251, 146, 124));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 255), null, null));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 311));

        txt_pin.setBackground(new java.awt.Color(251, 146, 124));
        txt_pin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_pin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_pinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_pinFocusLost(evt);
            }
        });
        txt_pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pinActionPerformed(evt);
            }
        });
        txt_pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pinKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pinKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter PIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        txt_enter_card.setBackground(new java.awt.Color(0, 0, 0));
        txt_enter_card.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        txt_enter_card.setForeground(new java.awt.Color(255, 255, 255));
        txt_enter_card.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_enter_cardFocusGained(evt);
            }
        });
        txt_enter_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_cardActionPerformed(evt);
            }
        });

        btn_n1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n1.setForeground(new java.awt.Color(249, 116, 92));
        btn_n1.setText("1");
        btn_n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n1ActionPerformed(evt);
            }
        });

        btn_n2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n2.setForeground(new java.awt.Color(249, 116, 92));
        btn_n2.setText("2");
        btn_n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n2ActionPerformed(evt);
            }
        });

        btn_n3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n3.setForeground(new java.awt.Color(249, 116, 92));
        btn_n3.setText("3");
        btn_n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n3ActionPerformed(evt);
            }
        });

        btn_n6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n6.setForeground(new java.awt.Color(249, 116, 92));
        btn_n6.setText("6");
        btn_n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n6ActionPerformed(evt);
            }
        });

        btn_n5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n5.setForeground(new java.awt.Color(249, 116, 92));
        btn_n5.setText("5");
        btn_n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n5ActionPerformed(evt);
            }
        });

        btn_n4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n4.setForeground(new java.awt.Color(249, 116, 92));
        btn_n4.setText("4");
        btn_n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n4ActionPerformed(evt);
            }
        });

        btn_n9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n9.setForeground(new java.awt.Color(249, 116, 92));
        btn_n9.setText("9");
        btn_n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n9ActionPerformed(evt);
            }
        });

        btn_n7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n7.setForeground(new java.awt.Color(249, 116, 92));
        btn_n7.setText("7");
        btn_n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n7ActionPerformed(evt);
            }
        });

        btn_n8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n8.setForeground(new java.awt.Color(249, 116, 92));
        btn_n8.setText("8");
        btn_n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n8ActionPerformed(evt);
            }
        });

        btn_n_dot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n_dot.setForeground(new java.awt.Color(249, 116, 92));
        btn_n_dot.setText(".");
        btn_n_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n_dotActionPerformed(evt);
            }
        });

        btn_n_blank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n_blank.setForeground(new java.awt.Color(0, 153, 153));
        btn_n_blank.setText(" ");

        btn_n0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_n0.setForeground(new java.awt.Color(249, 116, 92));
        btn_n0.setText("0");
        btn_n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n0ActionPerformed(evt);
            }
        });

        btn_ok.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ok.setText("OK");

        btn_clear.setBackground(new java.awt.Color(255, 153, 0));
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_enter.setBackground(new java.awt.Color(0, 153, 51));
        btn_enter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_enter.setForeground(new java.awt.Color(255, 255, 255));
        btn_enter.setText("Enter");
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Enter Card #");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_n_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_n0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_n_blank, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_l3)
                            .addComponent(lbl_l4)
                            .addComponent(lbl_l1)
                            .addComponent(lbl_l2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_enter_card))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_r2)
                    .addComponent(lbl_r1)
                    .addComponent(lbl_r3)
                    .addComponent(lbl_r4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbl_r1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_r2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_r3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_r4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_l1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_l2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_l3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_l4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_enter_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_n_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n_blank, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(516, 820));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_n3ActionPerformed(java.awt.event.ActionEvent evt) {

        //   Note: textbox_selection is use to identify which textbox is selected in the UI

        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+"3");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4) {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }

           else if(txt_enter_card.getText().length()==8) {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
          else if(txt_enter_card.getText().length()==12) {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
          
           txt_enter_card.setText(txt_enter_card.getText()+"3");
        }
        // TODO add your handling code here:
    }                                      

    private void btn_n5ActionPerformed(java.awt.event.ActionEvent evt) {
        //   Note: textbox_selection is use to identify which textbox is selected in the UI
        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+"5");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
           else if(txt_enter_card.getText().length()==8)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
          else if(txt_enter_card.getText().length()==12)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
            txt_enter_card.setText(txt_enter_card.getText()+"5");
           
        }

        // TODO add your handling code here:
    }

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {
        Customer cus= list.checkPinCard(txt_pin.getText(),txt_enter_card.getText());
        if(cus!=null)
        {
            this.setVisible(false);
            new ATMHOME(cus).setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid Card PIN or CARD #");
        }
        // TODO add your handling code here:
    }

    private void btn_n1ActionPerformed(java.awt.event.ActionEvent evt) {
        //   Note: textbox_selection is use to identify which textbox is selected in the UI
        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+"1");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
           else if(txt_enter_card.getText().length()==8)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
          else if(txt_enter_card.getText().length()==12)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
            txt_enter_card.setText(txt_enter_card.getText()+"1");
           
        }
// TODO add your handling code here:
    }                                      

    private void txt_pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pinActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pinActionPerformed

    private void txt_enter_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_cardActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_cardActionPerformed

    private void txt_pinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pinFocusGained
        textbox_selection=1;        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pinFocusGained

    private void txt_enter_cardFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_enter_cardFocusGained
        textbox_selection=2;    // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_cardFocusGained

    private void txt_pinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pinKeyTyped

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pinKeyTyped

    private void txt_pinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pinKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pinKeyPressed

    private void txt_pinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pinFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pinFocusLost

    private void btn_n2ActionPerformed(java.awt.event.ActionEvent evt) {
        //   Note: textbox_selection is use to identify which textbox is selected in the UI
        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+"2");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
           else if(txt_enter_card.getText().length()==8)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
          else if(txt_enter_card.getText().length()==12)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
            txt_enter_card.setText(txt_enter_card.getText()+"2");
           
        }        // TODO add your handling code here:
    }                                      

    private void btn_n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n4ActionPerformed
        //   Note: textbox_selection is use to identify which textbox is selected in the UI
        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+"4");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
           else if(txt_enter_card.getText().length()==8)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
          else if(txt_enter_card.getText().length()==12)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
            txt_enter_card.setText(txt_enter_card.getText()+"4");
           
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_n4ActionPerformed

    private void btn_n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n6ActionPerformed
        //   Note: textbox_selection is use to identify which textbox is selected in the UI
        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+"6");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
           else if(txt_enter_card.getText().length()==8)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
          else if(txt_enter_card.getText().length()==12)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
            txt_enter_card.setText(txt_enter_card.getText()+"6");
           
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_n6ActionPerformed

    private void btn_n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n7ActionPerformed

        //   Note: textbox_selection is use to identify which textbox is selected in the UI
        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+"7");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
           else if(txt_enter_card.getText().length()==8)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
          else if(txt_enter_card.getText().length()==12)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
            txt_enter_card.setText(txt_enter_card.getText()+"7");
           
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_n7ActionPerformed

    private void btn_n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n8ActionPerformed
        //   Note: textbox_selection is use to identify which textbox is selected in the UI
        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+"8");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
           else if(txt_enter_card.getText().length()==8)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
          else if(txt_enter_card.getText().length()==12)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
            txt_enter_card.setText(txt_enter_card.getText()+"8");
           
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_n8ActionPerformed

    private void btn_n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n9ActionPerformed
        //   Note: textbox_selection is use to identify which textbox is selected in the UI
        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+"9");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
           else if(txt_enter_card.getText().length()==8)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
          else if(txt_enter_card.getText().length()==12)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
            txt_enter_card.setText(txt_enter_card.getText()+"9");
           
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_n9ActionPerformed

    private void btn_n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n0ActionPerformed
        //   Note: textbox_selection is use to identify which textbox is selected in the UI
        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+"0");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
           else if(txt_enter_card.getText().length()==8)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
          else if(txt_enter_card.getText().length()==12)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
            txt_enter_card.setText(txt_enter_card.getText()+"0");
           
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_n0ActionPerformed

    private void btn_n_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n_dotActionPerformed
        //   Note: textbox_selection is use to identify which textbox is selected in the UI
        if(textbox_selection==1)
        {
          txt_pin.setText(txt_pin.getText()+".");
        
        }
        else if(textbox_selection==2)
        {
           if(txt_enter_card.getText().length()==4)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
           else if(txt_enter_card.getText().length()==8)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
           
          else if(txt_enter_card.getText().length()==12)
            
           {
              txt_enter_card.setText(txt_enter_card.getText()+" ");
           }
           
            txt_enter_card.setText(txt_enter_card.getText()+".");
           
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_n_dotActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed

        txt_pin.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed

this.setVisible(false);
new Home().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMPinConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMPinConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMPinConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMPinConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMPinConfirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_enter;
    private javax.swing.JButton btn_n0;
    private javax.swing.JButton btn_n1;
    private javax.swing.JButton btn_n2;
    private javax.swing.JButton btn_n3;
    private javax.swing.JButton btn_n4;
    private javax.swing.JButton btn_n5;
    private javax.swing.JButton btn_n6;
    private javax.swing.JButton btn_n7;
    private javax.swing.JButton btn_n8;
    private javax.swing.JButton btn_n9;
    private javax.swing.JButton btn_n_blank;
    private javax.swing.JButton btn_n_dot;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_l1;
    private javax.swing.JLabel lbl_l2;
    private javax.swing.JLabel lbl_l3;
    private javax.swing.JLabel lbl_l4;
    private javax.swing.JLabel lbl_r1;
    private javax.swing.JLabel lbl_r2;
    private javax.swing.JLabel lbl_r3;
    private javax.swing.JLabel lbl_r4;
    private javax.swing.JTextField txt_enter_card;
    private javax.swing.JTextField txt_pin;
    // End of variables declaration//GEN-END:variables
}
